---
- name: "CREATE ALL OBJECTS REQUIRED FOR THE NETWORK IMPORTER IN NETBOX"
  hosts: ["all"]
  gather_facts: false
  connection: "local"
  vars:
    device_roles: ["spine", "leaf", "router"]
    platforms:
      - {name: "junos", manufacturer: "juniper"}
      - {name: "iosxr", manufacturer: "cisco"}
      - {name: "ios", manufacturer: "cisco"}
      - {name: "nxos", manufacturer: "cisco"}
      - {name: "eos", manufacturer: "arista"}
    site_prefix: "ni_02"
    region: "ni_multi_site_02"
    sites: ["hou", "nyc", "sjc"]
    netbox_address: "{{ lookup('env','NETBOX_ADDRESS') }}"
    netbox_token: "{{ lookup('env','NETBOX_TOKEN') }}"

  tasks:
    - name: "01 CREATE REGION IN NETBOX"
      netbox.netbox.netbox_region:
        netbox_url: "{{ netbox_address }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: "{{ region }}"
        state: "present"
      run_once: true
      tags: ["region"]

    - name: "05 CREATE MANUFACTURER IN NETBOX"
      netbox.netbox.netbox_manufacturer:
        netbox_url: "{{ netbox_address }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: "{{ item.manufacturer }}"
        state: "present"
      loop: "{{platforms}}"
      run_once: true
      tags: ["manufacturer", "device_type"]

    - name: "10 CREATE DEVICE TYPE IN NETBOX"
      netbox.netbox.netbox_device_type:
        netbox_url: "{{ netbox_address }}"
        netbox_token: "{{ netbox_token }}"
        data:
          slug: "{{item.name}}"
          model: "{{item.name}}"
          manufacturer: "{{item.manufacturer}}"
          part_number: "{{item.name}}"
          u_height: 1
          is_full_depth: false
        state: "present"
      loop: "{{platforms}}"
      run_once: true
      tags: ["device_type"]

    - name: "15 CREATE DEVICE ROLE IN NETBOX"
      netbox.netbox.netbox_device_role:
        netbox_url: "{{ netbox_address }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: "{{item}}"
          color: "0000FF"
        state: "present"
      loop: "{{device_roles}}"
      run_once: true
      tags: ["device_role"]

    - name: "20 CREATE SITE IN NETBOX"
      netbox.netbox.netbox_site:
        netbox_url: "{{ netbox_address }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: "{{site_prefix}}_{{item}}"
          region: "{{ region }}"
        state: "present"
      loop: "{{sites}}"
      run_once: true
      tags: ["device_site"]

    - name: "25 CREATE DEVICES IN NETBOX"
      netbox.netbox.netbox_device:
        netbox_url: "{{ netbox_address }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: "{{inventory_hostname}}"
          device_type: "{{platform}}"
          device_role: "{{role}}"
          site: "{{site_prefix}}_{{site}}"
        state: "present"
      tags: ["device"]
