---
name: "CI"
on:
  - "push"
  - "pull_request"
jobs:
  black:
    env:
      INVOKE_LOCAL: "True"
    runs-on: "ubuntu-20.04"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v2"
      - name: "Setup environment"
        uses: "networktocode/gh-action-setup-poetry-environment@v2"
      - name: "Linting: Black"
        run: "poetry run invoke black"
  bandit:
    runs-on: "ubuntu-20.04"
    env:
      INVOKE_LOCAL: "True"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v2"
      - name: "Setup environment"
        uses: "networktocode/gh-action-setup-poetry-environment@v2"
      - name: "Linting: Bandit"
        run: "poetry run invoke bandit"
    needs:
      - "black"
  pydocstyle:
    runs-on: "ubuntu-20.04"
    env:
      INVOKE_LOCAL: "True"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v2"
      - name: "Setup environment"
        uses: "networktocode/gh-action-setup-poetry-environment@v2"
      - name: "Linting: pydocstyle"
        run: "poetry run invoke pydocstyle"
    needs:
      - "black"
  flake8:
    runs-on: "ubuntu-20.04"
    env:
      INVOKE_LOCAL: "True"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v2"
      - name: "Set up Python"
        uses: "actions/setup-python@v2"
        with:
          python-version: "3.9"
      - name: "Install Python Packages for Linting"
        run: "pip install --upgrade pip wheel invoke toml"
      - name: "Install Poetry Packages"
        run: |
          pip install poetry
          poetry config virtualenvs.create false
          poetry config installer.parallel false
          poetry install --no-interaction --no-ansi --no-root
      - name: "Linting: flake8"
        run: "poetry run invoke flake8"
    needs:
      - "black"
  yamllint:
    runs-on: "ubuntu-20.04"
    env:
      INVOKE_LOCAL: "True"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v2"
      - name: "Setup environment"
        uses: "networktocode/gh-action-setup-poetry-environment@v2"
      - name: "Linting: yamllint"
        run: "poetry run invoke yamllint"
    needs:
      - "black"
  build:
    runs-on: "ubuntu-20.04"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v2"
      - name: "Setup environment"
        uses: "networktocode/gh-action-setup-poetry-environment@v2"
      - name: "Build Container"
        run: "poetry run invoke build-image"
    needs:
      - "bandit"
      - "pydocstyle"
      - "flake8"
      - "yamllint"
  pylint:
    runs-on: "ubuntu-20.04"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v2"
      - name: "Setup environment"
        uses: "networktocode/gh-action-setup-poetry-environment@v2"
      - name: "Build Container"
        run: "poetry run invoke build-image"
      - name: "Linting: Pylint"
        run: "poetry run invoke pylint"
    needs:
      - "build"
  pytest:
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9"]
    runs-on: "ubuntu-20.04"
    env:
      PYTHON_VER: "${{ matrix.python-version }}"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v2"
      - name: "Setup environment"
        uses: "networktocode/gh-action-setup-poetry-environment@v2"
      - name: "Build Container"
        run: "poetry run invoke build-image"
      - name: "Run Tests"
        run: "poetry run invoke pytest"
    needs:
      - "pylint"
  integration_nautobot:
    name: "Integration Test - Nautobot"
    runs-on: "ubuntu-20.04"
    strategy:
      matrix:
        nautobot-version: ["1.0.3", "1.1.6", "1.2.12", "1.3.6", "latest"]
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v2"
      - name: "Set up Python"
        uses: "actions/setup-python@v2"
        with:
          python-version: "3.9"
      - name: "Run Install"
        run: |
          which pip
          pip -V
          pip install --upgrade pip wheel
          pip install invoke toml poetry pynautobot ansible==2.10.7
          ansible-galaxy collection install networktocode.nautobot:==2.0.1
          poetry config virtualenvs.create false
          poetry config installer.parallel false
          poetry install
          invoke nautobot-integration-tests
    env:
      NAUTOBOT_VERSION: "${{ matrix.nautobot-version }}"
    needs:
      - "pytest"
  integration_netbox210:
    name: "Integration Test - NetBox 2.10"
    runs-on: "ubuntu-20.04"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v2"
      - name: "Set up Python"
        uses: "actions/setup-python@v2"
        with:
          python-version: "3.9"
      - name: "Run Install"
        run: |
          which pip
          pip -V
          pip install invoke toml poetry pynetbox ansible==2.10.7
          ansible-galaxy collection install git+https://github.com/netbox-community/ansible_modules.git,v3.0.0
          poetry config virtualenvs.create false
          poetry config installer.parallel false
          poetry install
          invoke integration-tests
    env:
      NETBOX_VERSION: "v2.10"
    needs:
      - "pytest"
  integration_netbox29:
    name: "Integration Test - NetBox 2.9"
    runs-on: "ubuntu-20.04"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v2"
      - name: "Set up Python"
        uses: "actions/setup-python@v2"
        with:
          python-version: "3.9"
      - name: "Run Install"
        run: |
          which pip
          pip -V
          pip install invoke toml poetry pynetbox ansible==2.10.7
          ansible-galaxy collection install git+https://github.com/netbox-community/ansible_modules.git,v3.0.0
          poetry config virtualenvs.create false
          poetry config installer.parallel false
          poetry install
          invoke integration-tests
    env:
      NETBOX_VERSION: "v2.9"
    needs:
      - "pytest"
  integration_netbox28:
    name: "Integration Test - NetBox 2.8"
    runs-on: "ubuntu-20.04"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v2"
      - name: "Set up Python"
        uses: "actions/setup-python@v2"
        with:
          python-version: "3.9"
      - name: "Run Install"
        run: |
          which pip
          pip -V
          pip install invoke toml poetry pynetbox ansible==2.10.7
          ansible-galaxy collection install git+https://github.com/netbox-community/ansible_modules.git,v3.0.0
          poetry config virtualenvs.create false
          poetry config installer.parallel false
          poetry install
          invoke integration-tests
    env:
      NETBOX_VERSION: "v2.8"
    needs:
      - "pytest"
  publish_gh:
    name: "Publish to GitHub"
    runs-on: "ubuntu-20.04"
    if: "startsWith(github.ref, 'refs/tags/v')"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v2"
      - name: "Set up Python"
        uses: "actions/setup-python@v2"
        with:
          python-version: "3.9"
      - name: "Install Python Packages for Publishing"
        run: "pip install poetry"
      - name: "Set env"
        run: "echo RELEASE_VERSION=${GITHUB_REF:10} >> $GITHUB_ENV"
      - name: "Run Poetry Version"
        run: "poetry version $RELEASE_VERSION"
      - name: "Run Poetry Build"
        run: "poetry build"
      - name: "Upload binaries to release"
        uses: "svenstaro/upload-release-action@v2"
        with:
          repo_token: "${{ secrets.NTC_GITHUB_TOKEN }}"
          file: "dist/*"
          tag: "$RELEASE_VERSION"
          overwrite: true
          file_glob: true
    needs:
      - "integration_nautobot"
      - "integration_netbox210"
      - "integration_netbox29"
      - "integration_netbox28"
  publish_pypi:
    name: "Push Package to PyPI"
    runs-on: "ubuntu-20.04"
    if: "startsWith(github.ref, 'refs/tags/v')"
    steps:
      - name: "Check out repository code"
        uses: "actions/checkout@v2"
      - name: "Set up Python"
        uses: "actions/setup-python@v2"
        with:
          python-version: "3.9"
      - name: "Install Python Packages"
        run: "pip install poetry"
      - name: "Set env"
        run: "echo RELEASE_VERSION=${GITHUB_REF:10} >> $GITHUB_ENV"
      - name: "Run Poetry Version"
        run: "poetry version $RELEASE_VERSION"
      - name: "Run Poetry Build"
        run: "poetry build"
      - name: "Push to PyPI"
        uses: "pypa/gh-action-pypi-publish@release/v1"
        with:
          user: "__token__"
          password: "${{ secrets.PYPI_API_TOKEN }}"
    needs:
      - "integration_nautobot"
      - "integration_netbox210"
      - "integration_netbox29"
      - "integration_netbox28"
